import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  type DocumentData
} from "firebase/firestore";
import { getCmsFirebaseServices } from "../firebase/context";
import type { CmsContentSchema, CmsFieldSchema } from "../types/contentSchema";

export type DynamicDocumentRecord = {
  id: string;
  data: Record<string, unknown>;
};

export async function crearRegistroDocumento(
  schema: CmsContentSchema,
  data: Record<string, unknown>
): Promise<string> {
  const { firestore } = getCmsFirebaseServices();
  const payload = await applyAutogeneratedFields(schema, data);
  const response = await addDoc(collection(firestore, schema.collectionName), {
    ...payload,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
  return response.id;
}

export async function listarRegistrosDocumento(
  schema: CmsContentSchema,
  max = 100
): Promise<DynamicDocumentRecord[]> {
  const { firestore } = getCmsFirebaseServices();
  try {
    const q = query(
      collection(firestore, schema.collectionName),
      orderBy("createdAt", "desc"),
      limit(max)
    );
    const snapshot = await getDocs(q);
    return snapshot.docs.map((entry) => ({
      id: entry.id,
      data: entry.data() as DocumentData
    }));
  } catch {
    const fallback = await getDocs(collection(firestore, schema.collectionName));
    return fallback.docs.map((entry) => ({
      id: entry.id,
      data: entry.data() as DocumentData
    }));
  }
}

export async function eliminarRegistroDocumento(
  schema: CmsContentSchema,
  documentId: string
): Promise<void> {
  const { firestore } = getCmsFirebaseServices();
  await deleteDoc(doc(firestore, schema.collectionName, documentId));
}

export async function actualizarRegistroDocumento(
  schema: CmsContentSchema,
  documentId: string,
  data: Record<string, unknown>
): Promise<void> {
  const { firestore } = getCmsFirebaseServices();
  const payload = removeAutogeneratedFields(schema, data);
  await updateDoc(doc(firestore, schema.collectionName, documentId), {
    ...payload,
    updatedAt: serverTimestamp()
  });
}

const DEFAULT_DICTIONARY_DOC_ID = "main";
const DEFAULT_DICTIONARY_ROOT_KEY = "schema";

export async function guardarRegistroDiccionario(
  schema: CmsContentSchema,
  data: Record<string, unknown>,
  documentId = DEFAULT_DICTIONARY_DOC_ID
): Promise<string> {
  const { firestore } = getCmsFirebaseServices();
  const dictionaryId = schema.dictionaryDocumentId || documentId;
  const rootKey = resolveDictionaryRootKey(schema);
  const reference = doc(firestore, schema.collectionName, dictionaryId);
  const snapshot = await getDoc(reference);

  const payload: Record<string, unknown> = {
    updatedAt: serverTimestamp(),
    createdAt: snapshot.exists() ? snapshot.data().createdAt : serverTimestamp()
  };

  if (rootKey) {
    payload[rootKey] = data;
  } else {
    for (const [key, value] of Object.entries(data)) {
      payload[key] = value;
    }
  }

  await setDoc(
    reference,
    payload,
    { merge: true }
  );

  return dictionaryId;
}

export async function obtenerRegistroDiccionario(
  schema: CmsContentSchema,
  documentId = DEFAULT_DICTIONARY_DOC_ID
): Promise<DynamicDocumentRecord | null> {
  const { firestore } = getCmsFirebaseServices();
  const dictionaryId = schema.dictionaryDocumentId || documentId;
  const snapshot = await getDoc(doc(firestore, schema.collectionName, dictionaryId));

  if (!snapshot.exists()) {
    return null;
  }

  const raw = snapshot.data() as DocumentData;
  const rootKey = resolveDictionaryRootKey(schema);
  const nested = rootKey ? raw[rootKey] : null;

  if (nested && typeof nested === "object" && !Array.isArray(nested)) {
    return {
      id: snapshot.id,
      data: nested as Record<string, unknown>
    };
  }

  return {
    id: snapshot.id,
    data: raw
  };
}

function resolveDictionaryRootKey(schema: CmsContentSchema): string {
  if (schema.storageType !== "dictionary") {
    return "";
  }

  if (typeof schema.dictionaryRootKey === "string" && schema.dictionaryRootKey.trim()) {
    return schema.dictionaryRootKey.trim();
  }

  return DEFAULT_DICTIONARY_ROOT_KEY;
}

async function applyAutogeneratedFields(
  schema: CmsContentSchema,
  data: Record<string, unknown>
): Promise<Record<string, unknown>> {
  const autogeneratedFields = getAutogeneratedFields(schema);
  if (!autogeneratedFields.length) {
    return { ...data };
  }

  const { firestore } = getCmsFirebaseServices();
  const payload: Record<string, unknown> = { ...data };

  for (const field of autogeneratedFields) {
    if (field.type === "id") {
      payload[field.key] = await resolveNextOrdinalValue(firestore, schema.collectionName, field.key);
      continue;
    }

    if (field.type === "date") {
      payload[field.key] = new Date();
      continue;
    }
  }

  return payload;
}

function removeAutogeneratedFields(
  schema: CmsContentSchema,
  data: Record<string, unknown>
): Record<string, unknown> {
  const autogeneratedFields = getAutogeneratedFields(schema);
  if (!autogeneratedFields.length) {
    return { ...data };
  }

  const next = { ...data };
  for (const field of autogeneratedFields) {
    delete next[field.key];
  }
  return next;
}

function getAutogeneratedFields(schema: CmsContentSchema): CmsFieldSchema[] {
  if (schema.storageType !== "document") {
    return [];
  }
  return schema.fields.filter((field) => isFieldAutogenerated(field));
}

function isFieldAutogenerated(field: CmsFieldSchema): boolean {
  if (field.type === "id") {
    return true;
  }
  if (typeof field.autogenerated === "boolean") {
    return field.autogenerated;
  }
  return false;
}

async function resolveNextOrdinalValue(
  firestore: ReturnType<typeof getCmsFirebaseServices>["firestore"],
  collectionName: string,
  fieldKey: string
): Promise<number> {
  let max = 0;

  try {
    const highestSnapshot = await getDocs(
      query(
        collection(firestore, collectionName),
        orderBy(fieldKey, "desc"),
        limit(1)
      )
    );
    const highestValue = highestSnapshot.docs[0]?.data()?.[fieldKey];
    const highestOrdinal = toPositiveInteger(highestValue);
    if (highestOrdinal !== null) {
      max = highestOrdinal;
    }
  } catch {
    max = 0;
  }

  if (max > 0) {
    return max + 1;
  }

  const snapshot = await getDocs(collection(firestore, collectionName));
  for (const entry of snapshot.docs) {
    const candidate = toPositiveInteger(entry.data()?.[fieldKey]);
    if (candidate !== null && candidate > max) {
      max = candidate;
    }
  }

  return max + 1;
}

function toPositiveInteger(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) {
    const integer = Math.trunc(value);
    return integer >= 1 ? integer : null;
  }

  if (typeof value === "string") {
    const trimmed = value.trim();
    if (!trimmed) {
      return null;
    }
    const parsed = Number(trimmed);
    if (!Number.isFinite(parsed)) {
      return null;
    }
    const integer = Math.trunc(parsed);
    return integer >= 1 ? integer : null;
  }

  return null;
}
